FROM python:3.7.3-stretch
COPY ./src /resdb/src
RUN python -m pip install --upgrade pip
RUN python -m pip install grpcio
Run python -m pip install google-cloud
Run python -m pip install google-cloud-vision
Run python -m pip install better-abc