FROM python:3.7.3-stretch
COPY ./src /resdb/src
COPY ./src/ServerInformation/start_router.sh /resdb
WORKDIR "/resdb"
RUN python -m pip install --upgrade pip
RUN python -m pip install grpcio
Run python -m pip install google-cloud
Run python -m pip install google-cloud-vision
EXPOSE 50050
CMD ["/bin/bash", "start_server.sh"]