FROM python:3.7.3-stretch
ARG PORT
COPY ./src /resdb/src
COPY ./src/NamingService/start_server.sh /resdb
WORKDIR "/resdb"
RUN python -m pip install --upgrade pip
RUN python -m pip install grpcio
Run python -m pip install google-cloud
Run python -m pip install google-cloud-vision
EXPOSE $PORT
ENTRYPOINT ["/bin/bash", "start_server.sh"]