FROM python:3.7.3-stretch
COPY ./grpc /grpc
WORKDIR "/grpc"
RUN python -m pip install --upgrade pip
RUN python -m pip install grpcio
Run python -m pip install google-cloud
Run python -m pip install google-cloud-vision
EXPOSE 50051
CMD ["/bin/bash", "start_server.sh"]